# Generated by Django 4.1.2 on 2022-10-17 21:52

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('imagem_local', models.ImageField(null=True, upload_to=api.models.get_local_image_name, validators=[django.core.validators.validate_image_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('entregue', models.BooleanField(default=False)),
                ('imagem_objeto', models.ImageField(null=True, upload_to=api.models.get_objeto_image_name, validators=[django.core.validators.validate_image_file_extension])),
                ('dono_nome', models.CharField(max_length=255, null=True)),
                ('dono_cpf', models.CharField(max_length=11, null=True)),
                ('local_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.local')),
            ],
        ),
        migrations.AddField(
            model_name='local',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
