# Generated by Django 4.1.2 on 2022-10-24 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objeto',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
