# Generated by Django 4.1.2 on 2022-10-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_objeto_created_at_objeto_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
    ]
