# Generated by Django 4.1.2 on 2022-11-08 18:35

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_objeto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='dono_cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, null=True),
        ),
    ]
